// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDKtL__d79y8_boi5WKcnYsfg6bgJYLB0',
    appId: '1:486976281073:web:e9c7f864b046b0b3390c50',
    messagingSenderId: '486976281073',
    projectId: 'go-dantown',
    authDomain: 'go-dantown.firebaseapp.com',
    storageBucket: 'go-dantown.appspot.com',
    measurementId: 'G-WWFPRG0WTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEKpzBcVH6E1ICZ7RjUS0JFFXnKV3BmyM',
    appId: '1:486976281073:android:ea60784056badcd0390c50',
    messagingSenderId: '486976281073',
    projectId: 'go-dantown',
    storageBucket: 'go-dantown.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACI2KiCSLMG4VsdmH_KkdYywZizgn5zmg',
    appId: '1:486976281073:ios:bb231ca49f298d2d390c50',
    messagingSenderId: '486976281073',
    projectId: 'go-dantown',
    storageBucket: 'go-dantown.appspot.com',
    iosBundleId: 'com.dantown.dantownTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACI2KiCSLMG4VsdmH_KkdYywZizgn5zmg',
    appId: '1:486976281073:ios:bb231ca49f298d2d390c50',
    messagingSenderId: '486976281073',
    projectId: 'go-dantown',
    storageBucket: 'go-dantown.appspot.com',
    iosBundleId: 'com.dantown.dantownTest',
  );
}
